### ISSUE TITLE
How to install DSC Traek Pull Server

### ISSUE THREAD

**Issue by stefanstranger** [PowerShellOrg/dsc-traek#3]
How do I install and configure the DSC Traek Pull Server? 

I did the following to get the DSC Traek Pull Server installed and configured on Windows 2016 Server:

1. Installed NodeJS
2. Installed Node Modules express, winston and body-parser
3. Created some certificates and stored them in c:\data\certs folder
4. Tried to start Configuration by running npm start in folder .\scr\configuration

Error message:
```
2017-12-04T12:13:23.459Z - debug: Application configuration loaded for getAction Module from c:\temp\dsc-traek-master\src\configuration\appConfig.json.
_tls_common.js:104
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:104:17)
    at Server (_tls_wrap.js:803:25)
    at new Server (https.js:54:14)
    at Object.createServer (https.js:76:10)
    at Object.<anonymous> (c:\temp\dsc-traek-master\src\configuration\app.js:40:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dscnodes@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dscnodes@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ent.g001.s001\AppData\Roaming\npm-cache\_logs\2017-12-04T12_13_23_569Z-debug.log
```

More information about how to get start with the Traek DSC Pull server would be appreciated.

/Stefan

**Comment by grayzu** [comment]
Stefan,

First, let me note that the way that this has been designed is as a set of 6 Micro-Services. Second, there is currently no "single installer" as it is a work in progress.

Now as far as your question goes: In order to install / run this you need to do the following for each folder under dsc-traek/src/:
1. cd into the directory
2. run **npm install** to install all required modules and dependencies
3. run **npm start** to start the service

This will start the micro-service in the foreground so you will need to open another terminal window to run the next micro-service. I usually do this in VS Code with multiple consoles.

I know, this sounds terrible but this is just to work with this manually. Ideally this would be run as a set of containers that can be spun up quickly and as needed.

MarkG
